### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by joselito11** [sjthespian/addon-zwave-network-viewer#1]
I get instant erroron start:
```
15:30:11] INFO: Start HA Z-Wave Network Viewer
Traceback (most recent call last):
  File "webserver.py", line 3, in <module>
    from Managers.data_manager import HAZWaveManager
  File "/Managers/data_manager.py", line 12, in <module>
    import asyncws
ModuleNotFoundError: No module named 'asyncws'
```

**Comment by oldnasser** [comment]
I get the same error and in the system log I see this:
20-10-13 16:16:34 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.5:6123 ssl:default [Host is unreachable]

**Comment by sjthespian** [comment]
My guess is that there is a new module required by the viewer that I don't install in the docker image. I'm out of town for the next couple of days so won't have a chance to fix this until Monday. It should be an easy fix, but I don't have a way to test it from here.

**Comment by short4bmoney** [comment]
Same error for me but instead of `asyncws` it's:

```
ModuleNotFoundError: No module named 'flask'
```

**Comment by sjthespian** [comment]
I have a fix for the missing modules, but something else has changed that I have to track down. At the moment it starts, but never returns a page. I'm guessing something has change in the configuration that I have to match in the plugin.

**Comment by joselito11** [comment]
Thank you, it is working now.
